// <auto-generated />
using Assignment2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Assignment2.Entities.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistId");

                    b.ToTable("Idols");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            FirstName = "Minji",
                            LastName = "Kim"
                        },
                        new
                        {
                            ArtistId = 2,
                            FirstName = "Ryujin",
                            LastName = "Shin"
                        },
                        new
                        {
                            ArtistId = 3,
                            FirstName = "Yeji",
                            LastName = "Hwang"
                        },
                        new
                        {
                            ArtistId = 4,
                            FirstName = "Hanni",
                            LastName = "Pham"
                        });
                });

            modelBuilder.Entity("Assignment2.Entities.Song", b =>
                {
                    b.Property<int>("songId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("albumName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("songName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("songId");

                    b.ToTable("Music");

                    b.HasData(
                        new
                        {
                            songId = 1,
                            albumName = "Supernatural",
                            songName = "RightNow"
                        },
                        new
                        {
                            songId = 2,
                            albumName = "BornToBe",
                            songName = "RunAway"
                        },
                        new
                        {
                            songId = 3,
                            albumName = "ItzMe",
                            songName = "Wannabe"
                        },
                        new
                        {
                            songId = 4,
                            albumName = "NJWMX",
                            songName = "Ditto(250Remix)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
