@WebApiHost = https://localhost:7264

###

GET {{WebApiHost}}/api/Idols


###

GET {{WebApiHost}}/api/Idols/2

###

PUT {{WebApiHost}}/api/Idols
Content-Type: application/json

{
  "artistId": 2,
  "firstName": "Ryujin",
  "lastName": "Shin"
}

###


POST {{WebApiHost}}/api/Idols
Content-Type: application/json

{
  
  "firstName": "Lisa",
  "lastName": "Manoban"
}
 
###
DELETE {{WebApiHost}}/api/Idols/5


###

GET {{WebApiHost}}/api/Music


###

GET {{WebApiHost}}/api/Music/2

###

PUT {{WebApiHost}}/api/Music
Content-Type: application/json

{
  "songId": 1,
  "albumName": "Supernatural",
  "songName": "RightNow"
}

###


POST {{WebApiHost}}/api/Music
Content-Type: application/json

{
  
  "AlbumName": "BlackpinkIYA",
  "SongName": "BoomBayah-JapaneseVersion"
}
 
###
DELETE {{WebApiHost}}/api/Music/5